'''
CSC 579 - HW3
Peter DeAngelis
William Vukasovic

This file contains protocol commands for the secure remote file storage system. This
file is required by the client and server to send proper protocol commands.

'''
# constants defining protocol commands
CLIENT_HELLO = "CLIENT HELLO"
SERVER_HELLO = "SERVER HELLO"
KEY_EXCHANGE = "KEY_EXCHANGE"
SERVER_SESSION_BEGIN = "SERVER SESSION BEGIN"
CLIENT_SESSION_BEGIN = "CLIENT SESSION BEGIN"
CLIENT_AUTH = "CLIENT AUTH"
SERVER_AUTH_REPLY_AUTHORIZED = "SERVER AUTH REPLY AUTHORIZED"
SERVER_AUTH_REPLY_UNAUTHORIZED = "SERVER AUTH REPLY UNAUTHORIZED"
SERVER_AUTH_REPLY_TERMINATE = "SERVER AUTH REPLY TERMINATE"
CONNECTION_CLOSED = "CONNECTION_CLOSED"
FILE_UPLOAD_CMD = "PUT"
FILE_RETRIEVE_CMD = "GET"
EXIT_COMMAND = "BYE"
INVALID_COMMAND = "Invalid Command"
FNF_COMMAND = "FNF"